### ISSUE TITLE
Performance: wasting time by downloading unneeded data

### ISSUE THREAD

**Issue by shivtorov** [ucgeek/Get-TeamsAssignedNumbers#5]
This line of code downloads a couple of hundred attribute values for each user, but the script only using several attributes. Thus the time spent on downloading all other values are just wasted.

https://github.com/ucgeek/Get-TeamsAssignedNumbers/blob/9c545227e4dfc7ceae4907a0140f08b23d35f6d2/Get-TeamsAssignedNumbers.ps1#L53

Consider the following example - here we filter data in the cloud, and then only download the required values:
```
$sfboSession = New-CsOnlineSession
$UsersLineURI = Invoke-Command -Session $sfbSession -ScriptBlock { Get-CsOnlineUser -Filter 'LineURI -ne $null' | select-object DisplayName,LineURI } | select-object DisplayName,LineURI
```

**Comment by ucgeek** [comment]
@shivtorov thanks for all your points, I will definitely implement your feedback soon as I have a chance.
