### ISSUE TITLE
Module update

### ISSUE THREAD

**Issue by Mainframe79** [ucgeek/Get-TeamsAssignedNumbers#7]
Easy update to the script, but folks will need to use the new MicrosoftTeams module instead of the Skype one now

 Install-Module MicrosoftTeams -force -scope AllUsers
 Import-Module MicrosoftTeams
 Connect-MicrosoftTeams -Credential $cred

All the actual code still works, just need to update how you connect now.

**Comment by ucgeek** [comment]
The script already contains the Connect-MicrosoftTeams method. I have added a note re the install process.
